### ISSUE TITLE
Craft example

### ISSUE THREAD

**Issue by magicspon** [AlexandreKilian/craft-react#1]
Hello,

I don't suppose you have a working example I could look at.  I'm having some issues getting this to work.  Thanks

**Comment by AlexandreKilian** [comment]
@magicspon I am working on one, I will hopefully have a demo-project running soon!

**Comment by magicspon** [comment]
Aces...

**Comment by AlexandreKilian** [comment]
I have not forgotten about this, we're just implementing our first website with this plugin, and there are some learnings I want to integrate into a working example + some enhancements

**Comment by j2is** [comment]
Hey any update on a boilerplate example? Even just a work-in-progress would be really helpful :)

**Comment by AlexandreKilian** [comment]
> Hey any update on a boilerplate example? Even just a work-in-progress would be really helpful :)

just finishing up an important addition to the plugin, I'd prefer to do the demo with the updated plugin

**Comment by j2is** [comment]
Nice, can't wait!

**Comment by magicspon** [comment]
Snap!

**Comment by AlexandreKilian** [comment]
I've finally found some time to add the missing component to the plugin, that was keeping me from creating that demo project: serialization. It's in the new 1.1. release with some documentation, I will now start on getting that example project out!

**Comment by j2is** [comment]
Amazing thank you

**Comment by AlexandreKilian** [comment]
I've uploaded a basic demo of the plugin and our setup: https://github.com/AlexandreKilian/craft-react-demo
it could be cleaned up and documented more, but I wanted to get it out as quick as possible. I'm using the https://github.com/Firstborn/Craft-Migration-Manager Plugin to migrate Fields, Sections and Demo-Content for an easy setup
